plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.6'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${archives_base_name}-${minecraft_version}"
}


fabricApi {
    configureDataGeneration {
        client = true
    }
}

loom {
    accessWidenerPath = file("src/main/resources/touhou_little_maid.accesswidener")
    mixin {
        defaultRefmapName = "touhou_little_maid.refmap.json"
    }
    runs {
        datagen {
            property "fabric-api.datagen.modid", "touhou_little_maid"
        }
    }
}

repositories {
    // ./libs 目录为库
    flatDir {
        dir "libs"
    }
    // mavenLocal 为本机仓库
    mavenLocal()
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
            includeGroup "dev.architectury"
        }
    }
    maven {
        url "https://maven2.bai.lol"
        content {
            includeGroup "mcp.mobius.waila"
            includeGroup "lol.bai"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
        content {
            includeGroup "dev.emi"
        }
    }
    maven {
        name 'cursemaven'
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { // for TOP
        url "https://maven.k-4u.nl/"
        content {
            includeGroup "mcjty.theoneprobe"
        }
    }
    maven {
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup "top.theillusivec4.curios"
        }
    }
    maven {// CCA
        name = "Ladysnake Mods"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {// Forge Config API Port
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {// ModMenu
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "CottonMC"
        url = "https://server.bbkr.space/artifactory/libs-release"
    }
    maven {
        url = "https://maven.modmuss50.me/"
    }
    maven {
        name "reposiliteRepositoryArtifacts"
        url "https://maven.conczin.net/Artifacts"
    }
    maven { url = "https://maven.createmod.net" }
    maven { url 'https://maven.wispforest.io/releases' }
    maven { url 'https://maven.su5ed.dev/releases' }
    maven { url = "https://mvn.devos.one/releases/" }
    maven { url = "https://mvn.devos.one/snapshots/" }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    maven {
        url = "https://raw.github.com/Sh1roCu/Sh1roCu_MCRepo/master/repository"
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime

    mcLib
    implementation {
        extendsFrom mcLib
    }
    additionalRuntimeClasspath {
        extendsFrom mcLib
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    //mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // JS
    implementation(include("org.openjdk.nashorn:nashorn-core:15.4"))

    modCompileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    annotationProcessor 'com.google.code.findbugs:jsr305:3.0.2'

    // MP3 音频解码库，暂时不需要
    // mcLib "com.googlecode.soundlibs:mp3spi:1.9.5.4"
    // mcLib "com.googlecode.soundlibs:jlayer:1.0.1.4"
    // mcLib "com.googlecode.soundlibs:tritonus-share:0.3.7.4"

    // Opus 音频解码库
    mcLib("org.gagravarr:vorbis-java-core:0.8")
    mcLib("io.github.jaredmdobson:concentus:1.0.2")

    // YAML 库
    mcLib("org.yaml:snakeyaml:2.4")

    // 拆分出来的基岩版模型加载库
    // 又合并回来了
    // modImplementation(include("libs:simplebedrockmodel:1.3.0-fabric+mc1.21.1"))

    // JEI
    modImplementation "maven.modrinth:jei:${jei_version}"
    // REI
    modCompileOnly "maven.modrinth:architectury-api:${architectury_api_version}"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    modImplementation("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude group: 'net.fabricmc.fabric-api'
    }
    // EMI
    modCompileOnly "maven.modrinth:emi:${emi_version}"

    modImplementation "maven.modrinth:jade:${jade_version}"
    modImplementation "maven.modrinth:cyberanner-ironchest:${iron_chests_version}"
    modImplementation "maven.modrinth:carry-on:${carry_on_version}"
    modImplementation "maven.modrinth:patchouli:${patchouli_version}"

    // IPN
    modImplementation "net.fabricmc:fabric-language-kotlin:1.13.4+kotlin.2.2.0"
    modImplementation "maven.modrinth:libipn:fabric-1.21-6.5.0"
    modImplementation "maven.modrinth:inventory-profiles-next:fabric-1.21.1-2.1.8"

    modCompileOnly "maven.modrinth:sodium:mc1.21.1-0.6.13-fabric"
    modCompileOnly "maven.modrinth:iris:1.8.8+1.21.1-fabric"

    // CCA
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    modImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

    // Forge Config API Port
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.1.3"

    // ModMenu
    modImplementation("com.terraformersmc:modmenu:11.0.3")

    // Simple Hats
    modCompileOnly "maven.modrinth:simple-hats:nV0q5j3l"
    modCompileOnly "io.wispforest:accessories-fabric:1.1.0-beta.48+1.21.1"

    // Immersive Melodies
    modImplementation "immersive_melodies:immersive_melodies-fabric:0.6.2+1.21.1"

    // Ponder
    modImplementation("net.createmod.ponder:Ponder-Fabric-${minecraft_version}:1.0.61")

    // 精妙背包
    modCompileOnly("libs:sophisticatedbackpacks:1.21.1-3.23.4.3.106")
    modCompileOnly("libs:sophisticatedcore:1.21.1-1.2.9.17.157")
    modCompileOnly(files("libs/compile_only/core-3.1.0-beta.47+1.21.1.jar"))
    modCompileOnly(files("libs/compile_only/transfer-3.1.0-beta.47+1.21.1.jar"))

    // 森罗物语：烹饪
    modCompileOnly "maven.modrinth:kaleidoscope-cookery:1.0.1-fabric+mc1.21.1"

    // Improved Mobs
    modImplementation "maven.modrinth:improved-mobs:1.21.1-1.14.2-fabric"
    modImplementation "maven.modrinth:tenshilib:1.21.1-2.1.1-fabric"

    // TACZ
    modImplementation("libs:TACZ-Refabricated:1.21.1-0.0.7")
    implementation(minecraftLibraries('org.apache.commons:commons-math3:3.6.1'))
    implementation('com.github.FiguraMC.luaj:luaj-core:3.0.8-figura') {
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    implementation('com.github.FiguraMC.luaj:luaj-jse:3.0.8-figura') {
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    implementation('org.apache.bcel:bcel:6.6.1') {
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    modImplementation "curse.maven:nonconflictkeys-fabric-865546:4572953"

    // PatPat
    modImplementation "maven.modrinth:patpat:1.2.1+1.21.1"
    modImplementation "maven.modrinth:proxlib:0.2.4+1.21"
    modImplementation "maven.modrinth:fabric-permissions-api:0.3.1"

    // 卓越前线
    modCompileOnly "software.bernie.geckolib:geckolib-fabric-1.21.1:4.7.5"
    // TODO: 1.21没移植完，暂时用1.20通过编译
    modCompileOnly(files("libs/compile_only/superbwarfare-fabric-0.0.1-forge0.8.7.jar"))

    // 地图相关模组兼容
    modRuntimeOnly "maven.modrinth:xaeros-minimap:25.2.10_Fabric_1.21"
    modRuntimeOnly "maven.modrinth:xaeros-world-map:1.39.12_Fabric_1.21"

    // 拔刀剑
    modImplementation "cn.sh1rocu:slashblade-refabricated:1.21.1-1.0.1-Resharped-1.7.55"

    // 不加就无法run的各种前置
    modImplementation "io.github.cottonmc:LibGui:11.1.0+1.21"
    modImplementation "me.zeroeightsix:fiber:0.23.0-SNAPSHOT"
}

shadowJar {
    configurations = [project.configurations.mcLib]

    dependencies {
        exclude(dependency('junit:junit'))
    }

    archiveClassifier.set("shadow")

    relocationPrefix = "com.github.tartaricacid.touhoulittlemaid.libs"
    enableRelocation = true

    exclude 'META-INF/maven/**/*'
    exclude 'META-INF/versions/**/*'
    exclude 'META-INF/LICENSE'
    exclude '.cache/**'

    mergeServiceFiles()
    minimize()
}

remapJar {
    dependsOn(shadowJar)
    inputFile = shadowJar.archiveFile
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.WARN
}
tasks.withType(Zip).configureEach {
    duplicatesStrategy = DuplicatesStrategy.WARN
}
tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE-MIT") {
        rename { "${it}_${project.archivesBaseName}" }
    }
    from("LICENSE-CC") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = "${project.archives_base_name}-${project.minecraft_version}"
            from components.java
        }
    }

    repositories {
        maven {
            url "file:///D:/github_maven/Sh1roCu_MCRepo/repository"
        }
    }
}
