# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.2
# Mod Properties
mod_version=1.0.0-neo2.0.0+mc26.2
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-fabric
# Dependencies
fabric_version=0.153.0+26.2
jei_version=30.2.0.15-fabric
cloth_config_version=26.2.155
jade_version=26.2.3+fabric
# TODO: 等26.2发布
patchouli_version=26.1-94-beta

