# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
loader_version=0.17.2
# Mod Properties
mod_version=0.5.1-neo1.4.6
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-fabric
# Dependencies
fabric_version=0.116.4+1.21.1
jei_version=19.22.1.316-fabric
architectury_api_version=13.0.6+fabric
rei_version=16.0.744
emi_version=1.1.10+1.21+fabric
cloth_config_version=15.0.128
jade_version=15.10.1+fabric
iron_chests_version=2.0.4
carry_on_version=2.2.2-fabric
patchouli_version=1.21-87-fabric
cca_version=6.1.2
