# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.19.2
# Mod Properties
mod_version=0.8.0-neo1.5.3+mc26.1
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-fabric
# Dependencies
fabric_version=0.145.4+26.1.1
jei_version=29.5.0.28-fabric
architectury_api_version=13.0.6+fabric
rei_version=16.0.744
emi_version=1.1.10+1.21+fabric
cloth_config_version=26.1.154
jade_version=26.0.8+fabric
iron_chests_version=2.0.5
carry_on_version=2.2.4-fabric
patchouli_version=1.21-87-fabric
cca_version=8.0.0
